### ISSUE TITLE
Unit tests fail

### ISSUE THREAD

**Issue by taboubi** [mudrd8mz/moodle-workshopeval_credit#1]
Hi David,
When I run unit tests I got this error:
`1) workshopeval_credit_testcase::test_calculate_assessment_grades_empty
Undefined property: stdClass::$id`

Moodle 3.3.1

**Comment by mudrd8mz** [comment]
Sorry, I forgot to comment here that I had reproduced the failure. I don't think I will be able to work on this particular bug anytime soon myself. Pull requests welcome. Thanks.

**Comment by mudrd8mz** [comment]
Actually, this turned out to be a different problem. It seems that Github was a bit buggy. Even when the default branch had been set to master, after cloning the repository the legacy branch MOODLE_24_STABLE was checked out. And on that branch, the reported unit test failure was experienced.

I re-set the default branch to be really the master as expected. I can confirm that on master branch, the unit tests pass as expected.
